config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :my_templates

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/my_template.rb
class MyTemplate < ActiveRecord::Base

  validates :my_template_name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/my_templates_controller.rb
class MyTemplatesController < ApplicationController
  before_action :set_my_template, only: [:show, :edit, :update, :destroy]

  # GET /my_templates
  # GET /my_templates.json
  def index
    @my_templates = MyTemplate.all
  end

  # GET /my_templates/1
  # GET /my_templates/1.json
  def show
  end

  # GET /my_templates/new
  def new
    @my_template = MyTemplate.new
  end

  # GET /my_templates/1/edit
  def edit
  end

  # POST /my_templates
  # POST /my_templates.json
  def create
    @my_template = MyTemplate.new(my_template_params)

    respond_to do |format|
      if @my_template.save
        format.html { redirect_to @my_template, notice: 'My template was successfully created.' }
        format.json { render :show, status: :created, location: @my_template }
      else
        format.html { render :new }
        format.json { render json: @my_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_templates/1
  # PATCH/PUT /my_templates/1.json
  def update
    respond_to do |format|
      if @my_template.update(my_template_params)
        format.html { redirect_to @my_template, notice: 'My template was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_template }
      else
        format.html { render :edit }
        format.json { render json: @my_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_templates/1
  # DELETE /my_templates/1.json
  def destroy
    @my_template.destroy
    respond_to do |format|
      format.html { redirect_to my_templates_url, notice: 'My template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_template
      @my_template = MyTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_template_params
      params.require(:my_template).permit(:my_template_name, :my_template_type, :my_template_body)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/my_templates_helper.rb
module MyTemplatesHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProvisioningEngineTemplates</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- Prelang: Analytics / Google Analytics -->
    <%= analytics_init if Rails.env.production? or Rails.env.development? %><meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/my_templates/_form.html.erb
<%= form_for @my_template, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :my_template_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :my_template_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :my_template_type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :my_template_type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :my_template_body, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :my_template_body, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  my_templates_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/my_templates/edit.html.erb
<%- model_class = MyTemplate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => MyTemplate %></h1>
</div>
<%= render :partial => 'form' %>

app/views/my_templates/index.html.erb
<%- model_class = MyTemplate -%>
<div class="page-header">
  <h1><%=t '.title', :default => MyTemplate %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:my_template_name) %></th>
      <th><%= model_class.human_attribute_name(:my_template_type) %></th>
      <th><%= model_class.human_attribute_name(:my_template_body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @my_templates.each do |my_template| %>
      <tr>
        <td><%= my_template.id %></td>
        <td><%= my_template.my_template_name %></td>
        <td><%= my_template.my_template_type %></td>
        <td><%= my_template.my_template_body %></td>
        <td><%=l my_template.created_at, format: :long %></td>
        <td>
          <%= link_to my_template_path(my_template), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to my_template_path(my_template), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_my_template_path,
            :class => 'btn btn-primary' %>

app/views/my_templates/new.html.erb
<%- model_class = MyTemplate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => MyTemplate %></h1>
</div>
<%= render :partial => 'form' %>

app/views/my_templates/show.html.erb
<%- model_class = MyTemplate -%>
<div class="page-header">
  <h1><%=t '.title', :default => MyTemplate %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:my_template_name) %></dt>
      <dd><pre class="prettyprint"><%= @my_template.my_template_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:my_template_type) %></dt>
      <dd><pre class="prettyprint"><%= @my_template.my_template_type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:my_template_body) %></dt>
      <dd><pre class="prettyprint"><%= @my_template.my_template_body %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              my_templates_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_my_template_path(@my_template), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              my_template_path(@my_template),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>